"""added name

Revision ID: 5a06b83c6fd8
Revises: 4e1730b662d3
Create Date: 2024-12-01 02:51:04.052635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a06b83c6fd8'
down_revision: Union[str, None] = '4e1730b662d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family', 'name')
    # ### end Alembic commands ###
