"""fixed

Revision ID: cd89acc6da0d
Revises: 5a06b83c6fd8
Create Date: 2024-12-01 03:25:07.926058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd89acc6da0d'
down_revision: Union[str, None] = '5a06b83c6fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_family_id_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_family_id_key', 'user', ['family_id'])
    # ### end Alembic commands ###
